name: Continuous Integration

on: [pull_request, push]

jobs:
  windows-2019:
    name: Windows Server 2019
    runs-on: windows-2019
    steps:
      - uses: actions/setup-go@v1
        with:
          go-version: 1.14
      - uses: actions/checkout@v2

      - name: Test
        run: go test ./...

  ubuntu-18-04:
    name: Ubuntu 18.04
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/setup-go@v1
        with:
          go-version: 1.14
      - uses: actions/checkout@v2

      - name: Install dependencies
        run: |
          sudo apt-get install libgl1-mesa-dev
          sudo apt-get install libglfw3-dev

      - name: Test
        run: go test ./...

  macos-10-15:
    name: macOS Catalina 10.15
    runs-on: macos-10.15
    steps:
      - uses: actions/setup-go@v1
        with:
          go-version: 1.14
      - uses: actions/checkout@v2

      - name: Install dependencies
        run: |
          brew install glfw3
          ln -s /usr/local/lib/libglfw3.dylib /usr/local/lib/libglfw.dylib

      - name: Test
        run: go test ./...
